// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRM6mNz5J6fpePQdT495lln0ctboUVyo',
    appId: '1:327779298654:web:f994b3a053d31f9d9173cf',
    messagingSenderId: '327779298654',
    projectId: 'cymarket-051c1',
    authDomain: 'cymarket-051c1.firebaseapp.com',
    storageBucket: 'cymarket-051c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCesmiK8buD_E46V8BUhqvq7tm8zbNtMEA',
    appId: '1:327779298654:android:852b1a5af37320e19173cf',
    messagingSenderId: '327779298654',
    projectId: 'cymarket-051c1',
    storageBucket: 'cymarket-051c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmlJu1eo5IKIyDW_YFD203X_2_Ljo7QSM',
    appId: '1:327779298654:ios:34cac426a8b65a969173cf',
    messagingSenderId: '327779298654',
    projectId: 'cymarket-051c1',
    storageBucket: 'cymarket-051c1.appspot.com',
    iosClientId: '327779298654-05hvsnet4cj03f4p6bsbecrgnlce0heb.apps.googleusercontent.com',
    iosBundleId: 'com.fm.cymarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmlJu1eo5IKIyDW_YFD203X_2_Ljo7QSM',
    appId: '1:327779298654:ios:34cac426a8b65a969173cf',
    messagingSenderId: '327779298654',
    projectId: 'cymarket-051c1',
    storageBucket: 'cymarket-051c1.appspot.com',
    iosClientId: '327779298654-05hvsnet4cj03f4p6bsbecrgnlce0heb.apps.googleusercontent.com',
    iosBundleId: 'com.fm.cymarket',
  );
}
